# Generated by Django 6.0.5 on 2026-05-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='scholarship',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='group_name',
            field=models.CharField(default='0000000000', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='IPZ-21', max_length=30),
            preserve_default=False,
        ),
    ]
